<?php
/**
 * @category    design
 * @package     default_default
 */
?>
<div class="page-title">
    <h1 id="message"><?php echo $this->__('Thank you for your registration with %s', Mage::app()->getStore()->getFrontendName()) ?></h1>
</div>
<h2 class="sub-title">
    <?php /*echo $this->__('You will receive a registration confirmation email with details of your login information.')*/ ?>
 </h2>
<p><?php echo $this->__("The registration process is pending for administrator's approval.") ?></p>
<p><?php echo $this->__('You will be notified once it has been approved.') ?></p>
